export const COUNTRY_CODES = [
  { code: '+61', flag: '🇦🇺', countryCode: 'AU', name: 'Australia' },
  { code: '+55', flag: '🇧🇷', countryCode: 'BR', name: 'Brazil' },
  { code: '+86', flag: '🇨🇳', countryCode: 'CN', name: 'China' },
  { code: '+20', flag: '🇪🇬', countryCode: 'EG', name: 'Egypt' },
  { code: '+33', flag: '🇫🇷', countryCode: 'FR', name: 'France' },
  { code: '+49', flag: '🇩🇪', countryCode: 'DE', name: 'Germany' },
  { code: '+233', flag: '🇬🇭', countryCode: 'GH', name: 'Ghana' },
  { code: '+91', flag: '🇮🇳', countryCode: 'IN', name: 'India' },
  { code: '+39', flag: '🇮🇹', countryCode: 'IT', name: 'Italy' },
  { code: '+81', flag: '🇯🇵', countryCode: 'JP', name: 'Japan' },
  { code: '+31', flag: '🇳🇱', countryCode: 'NL', name: 'Netherlands' },
  { code: '+234', flag: '🇳🇬', countryCode: 'NG', name: 'Nigeria' },
  { code: '+7', flag: '🇷🇺', countryCode: 'RU', name: 'Russia' },
  { code: '+966', flag: '🇸🇦', countryCode: 'SA', name: 'Saudi Arabia' },
  { code: '+27', flag: '🇿🇦', countryCode: 'ZA', name: 'South Africa' },
  { code: '+82', flag: '🇰🇷', countryCode: 'KR', name: 'South Korea' },
  { code: '+34', flag: '🇪🇸', countryCode: 'ES', name: 'Spain' },
  { code: '+46', flag: '🇸🇪', countryCode: 'SE', name: 'Sweden' },
  { code: '+971', flag: '🇦🇪', countryCode: 'AE', name: 'United Arab Emirates' },
  { code: '+44', flag: '🇬🇧', countryCode: 'UK', name: 'United Kingdom' },
  { code: '+1', flag: '🇺🇸', countryCode: 'US', name: 'United States' },
]
